const starterRecipes = [
  {id:'cinnamon-rolls',title:'سينامون رول طري',category:'حلويات',tags:['مخبوزات','حلويات'],time:125,emoji:'🥮',art:'cinnamon',description:'لفائف قرفة دافئة بقلب طري وصوص جبن كريمي يذوب فوقها.',servings:'9–10 حبات',ingredients:['500 جم دقيق أبيض','250 مل حليب دافئ','7 جم خميرة فورية','70 جم سكر','1 بيضة كبيرة','60 جم زبدة طرية','½ ملعقة صغيرة ملح','1 ملعقة صغيرة فانيليا','للحشوة: 80 جم زبدة طرية','120 جم سكر بني','1½–2 ملعقة كبيرة قرفة','للصوص: 100 جم جبن كريمي','40 جم زبدة طرية','80–100 جم سكر بودرة','فانيليا و1–2 ملعقة كبيرة حليب','اختياري: 60 مل كريمة خفق دافئة'],steps:['اخلطي الحليب الدافئ مع الخميرة وقليل من السكر واتركيه 5 دقائق. أضيفي البيضة وباقي السكر والفانيليا.','أضيفي الدقيق والملح واعجني 6–8 دقائق، ثم أضيفي الزبدة تدريجيًا واستمري حتى تصبح العجينة ناعمة ومطاطية.','غطي العجينة واتركيها تختمر حتى يتضاعف حجمها، حوالي ساعة. افرديها مستطيلًا وادهنيها بالزبدة، ثم وزعي السكر البني والقرفة.','لفي العجينة على شكل رول وقطعيها إلى 9 أو 10 قطع. رتبيها في الصينية واتركيها تختمر 30–45 دقيقة.','اسكبي الكريمة الدافئة بين الحبات إذا رغبتِ، ثم اخبزيها على 175°م لمدة 20–25 دقيقة حتى يصبح لونها ذهبيًا خفيفًا.','اخلطي مكونات الصوص ووزعيه على السينامون وهو دافئ.'],favorite:false,rating:0,note:''},
  {id:'quick-sandwich-bread',title:'خبز ساندويتش دائري سريع',category:'فطور',tags:['مخبوزات','فطور'],time:25,emoji:'🥯',art:'quickbread',description:'خبز زبادي سريع على المقلاة؛ طري ودافئ، مناسب لساندويتش خفيف.',servings:'6 حبات',ingredients:['2 كوب دقيق','1 كوب زبادي','2 ملعقة صغيرة بيكنج باودر','½ ملعقة صغيرة ملح','1 ملعقة صغيرة سكر','1 ملعقة كبيرة زيت','زبدة خفيفة للدهن بعد الخبز (اختياري)'],steps:['اخلطي الدقيق والبيكنج باودر والملح والسكر. أضيفي الزبادي والزيت واعجني 2–3 دقائق حتى تتكون عجينة ناعمة.','إذا كانت العجينة لاصقة جدًا، أضيفي رشة دقيق بسيطة فقط. قسميها إلى 6 كرات.','افردي كل كرة بشكل دائري بسماكة نحو 1 سم.','سخني مقلاة على نار متوسطة، واطهي كل خبزة 2–3 دقائق لكل جهة. اقلبيها واضغطي برفق حول الأطراف حتى تستوي من الداخل.','ادهنيها بلمسة زبدة وغطيها بفوطة نظيفة 5 دقائق لتبقى طرية.'],favorite:false,rating:0,note:''}
];
// US cup = 240 ml. Flour is spooned into the cup and levelled; gram/cup values
// for sugar and butter are practical kitchen equivalents, while spoon measures stay unchanged.
const starterMeasures={
  'cinnamon-rolls':{
    metric:['500 جم دقيق أبيض','250 مل حليب دافئ','7 جم خميرة فورية','70 جم سكر','1 بيضة كبيرة','60 جم زبدة طرية','½ ملعقة صغيرة ملح','1 ملعقة صغيرة فانيليا','للحشوة: 80 جم زبدة طرية','120 جم سكر بني','1½–2 ملعقة كبيرة قرفة','للصوص: 100 جم جبن كريمي','40 جم زبدة طرية','80–100 جم سكر بودرة','فانيليا و1–2 ملعقة كبيرة حليب','اختياري: 60 مل كريمة خفق دافئة'],
    cups:['4 أكواب دقيق أبيض (بالملعقة ثم يُسوّى)','1 كوب + 2 ملعقة صغيرة حليب دافئ','2¼ ملعقة صغيرة خميرة فورية','⅓ كوب + 1 ملعقة صغيرة سكر','1 بيضة كبيرة','¼ كوب + 1 ملعقة صغيرة زبدة طرية','½ ملعقة صغيرة ملح','1 ملعقة صغيرة فانيليا','للحشوة: ⅓ كوب + 1 ملعقة صغيرة زبدة طرية','½ كوب + 1 ملعقة صغيرة سكر بني معبأ','1½–2 ملعقة كبيرة قرفة','للصوص: ⅓ كوب + 1 ملعقة كبيرة جبن كريمي','2 ملعقة كبيرة + 2 ملعقة صغيرة زبدة طرية','⅔–¾ كوب سكر بودرة، حسب القوام','فانيليا و1–2 ملعقة كبيرة حليب','اختياري: ¼ كوب كريمة خفق دافئة']
  },
  'quick-sandwich-bread':{
    metric:['250 جم دقيق (يعادل كوبين ممسوحين)','245 جم زبادي','8 جم بيكنج باودر','3 جم ملح','4 جم سكر','15 مل زيت (نحو 14 جم)','قليل من الزبدة للدهن (اختياري)'],
    cups:['2 كوب دقيق، يُملأ بالملعقة ويُسوّى','1 كوب زبادي','2 ملعقة صغيرة بيكنج باودر','½ ملعقة صغيرة ملح','1 ملعقة صغيرة سكر','1 ملعقة كبيرة زيت','قليل من الزبدة للدهن (اختياري)']
  }
};
const STORE='juri-cooks-recipes-v1',TRAY_STORE='juri-cooks-tray-v1',CHECK_STORE='juri-cooks-checks-v1'; let recipes=loadRecipes(); let activeCategory='الكل'; let currentRecipe=null; let cookStep=0; let toastTimer; let bakingTray=loadTray(); let checkedItems=loadChecks(); let ovenTimerHandle=null; let ovenSeconds=0; let pickInterval=null;
let measurementMode=localStorage.getItem('juri-cooks-measure-v1')==='cups'?'cups':'metric';
function loadRecipes(){try{const saved=JSON.parse(localStorage.getItem(STORE));if(Array.isArray(saved)){const ids=new Set(saved.map(r=>r.id));return [...starterRecipes.filter(r=>!ids.has(r.id)),...saved]}}catch{}return structuredClone(starterRecipes)}
function save(){localStorage.setItem(STORE,JSON.stringify(recipes));updateCounts()}
function updateCounts(){document.querySelector('#recipeCount').textContent=recipes.length;document.querySelector('#favoriteCount').textContent=recipes.filter(r=>r.favorite).length;document.querySelector('#bakeCount').textContent=recipes.reduce((n,r)=>n+(r.bakeCount||0),0);document.querySelector('#trayCount').textContent=bakingTray.length;const mobile=document.querySelector('#mobileTrayCount');if(mobile)mobile.textContent=bakingTray.length}
function ingredientLabel(recipe,index){const measures=starterMeasures[recipe.id];if(!measures)return recipe.ingredients[index];return (measures[measurementMode]||measures.metric)[index]||recipe.ingredients[index]}
function measurementControl(recipe){if(!starterMeasures[recipe.id])return '<p class="measure-note">مقاديرك محفوظة كما أدخلتِها.</p>';return `<div class="measure-control" role="group" aria-label="اختيار وحدة القياس"><button type="button" data-unit="metric" class="${measurementMode==='metric'?'active':''}" aria-pressed="${measurementMode==='metric'}">جرامات</button><button type="button" data-unit="cups" class="${measurementMode==='cups'?'active':''}" aria-pressed="${measurementMode==='cups'}">أكواب وملاعق</button></div><p class="measure-note">الكوب المعياري 240 مل. الدقيق يُملأ بالملعقة ويُسوّى؛ وبعض تحويلات الزبدة والسكر تقريبية منزليًا.</p>`}
function setMeasurementMode(mode){if(!['metric','cups'].includes(mode)||measurementMode===mode)return;measurementMode=mode;localStorage.setItem('juri-cooks-measure-v1',mode);if(currentRecipe&&document.querySelector('#recipeModal:not(.hidden)'))openRecipe(currentRecipe.id);renderTray()}
function escapeHtml(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function updateFilters(){const fixed=['مخبوزات','فطور','حلويات'];const dynamic=[...new Set(recipes.map(r=>r.category).filter(c=>!fixed.includes(c)&&c!=='الكل'&&c!=='المفضّلة'))];const cats=['الكل',...fixed,...dynamic,'المفضّلة'];document.querySelector('#filters').innerHTML=cats.map(c=>{const count=c==='الكل'?recipes.length:c==='المفضّلة'?null:recipes.filter(r=>r.category===c||r.tags?.includes(c)).length;return `<button class="filter ${activeCategory===c?'active':''}" data-category="${escapeHtml(c)}">${c==='المفضّلة'?'♡ ':''}${escapeHtml(c)}${count!==null?` <span>${String(count).padStart(2,'0')}</span>`:''}</button>`}).join('')}
function render(){updateFilters();const query=document.querySelector('#searchInput').value.trim().toLowerCase();const shown=recipes.filter(r=>{const matchCat=activeCategory==='الكل'||(activeCategory==='المفضّلة'?r.favorite:r.category===activeCategory||r.tags?.includes(activeCategory));const matchText=!query||`${r.title} ${r.description} ${r.category}`.toLowerCase().includes(query);return matchCat&&matchText});const grid=document.querySelector('#recipeGrid');grid.innerHTML=shown.map((r,i)=>`<article class="recipe-card" style="animation-delay:${i*70}ms"><div class="card-art ${escapeHtml(r.art||'custom')}"><div class="art-shape"></div><span class="food-emoji">${escapeHtml(r.emoji||'🍰')}</span><span class="art-doodle doodle-a">✳</span><span class="art-doodle doodle-b">✿</span><span class="art-doodle doodle-c">·</span><span class="card-chip">${escapeHtml(r.category)}</span><button class="favorite-btn ${r.favorite?'is-favorite':''}" data-fav="${escapeHtml(r.id)}" aria-label="${r.favorite?'إزالة من':'إضافة إلى'} المفضلة">${r.favorite?'♥':'♡'}</button></div><div class="card-body"><div class="card-meta"><span>${escapeHtml(r.tags?.[0]||r.category)}</span><span>${r.bakeCount?`✦ خبزتها ${r.bakeCount} مرة`:r.rating?`★ ${r.rating}/5`:'من دفتر جوري'}</span></div><h3 class="card-title">${escapeHtml(r.title)}</h3><p class="card-desc">${escapeHtml(r.description||'وصفة جديدة من دفتر جوري.')}</p><div class="card-bottom"><span class="card-time"><b>${r.time||30}</b> دقيقة · ${escapeHtml(r.servings||'تقدّم بمحبة')}</span><div class="card-actions"><button class="tray-add ${bakingTray.includes(r.id)?'in-tray':''}" data-tray="${escapeHtml(r.id)}">${bakingTray.includes(r.id)?'✓ بالصينية':'+ للصينية'}</button><button class="open-recipe" data-open="${escapeHtml(r.id)}">افتحي الوصفة <span>←</span></button></div></div></div></article>`).join('');document.querySelector('#emptyState').classList.toggle('hidden',shown.length>0);grid.classList.toggle('show-all',shown.length>2);updateCounts()}
function showToast(message){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2300)}
function showModal(el){el.classList.remove('hidden');document.body.style.overflow='hidden'}function hideModal(el){el.classList.add('hidden');document.body.style.overflow=''}
function openRecipe(id){const r=recipes.find(x=>x.id===id);if(!r)return;currentRecipe=r;const detail=document.querySelector('#recipeDetail');detail.innerHTML=`<div class="detail-head"><div class="detail-illustration ${escapeHtml(r.art||'custom')}">${escapeHtml(r.emoji||'🍰')}</div><div><div class="detail-kicker">${escapeHtml(r.category)} · من دفتر جوري</div><h2>${escapeHtml(r.title)}</h2><p>${escapeHtml(r.description||'وصفة جديدة من دفتر جوري.')}</p><div class="detail-meta"><span>◷ ${r.time||30} دقيقة</span><span>♡ ${escapeHtml(r.servings||'على مزاجك')}</span></div></div></div><div class="detail-columns"><section><div class="ingredient-heading"><h3>المقادير <span>(${r.ingredients.length})</span></h3>${measurementControl(r)}</div><ul class="ingredient-list">${r.ingredients.map((x,i)=>`<li>${escapeHtml(ingredientLabel(r,i))}</li>`).join('')}</ul></section><section><h3>الطريقة <span>(${r.steps.length} خطوات)</span></h3><ol class="steps-list">${r.steps.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ol></section></div><div class="detail-actions"><button class="cook-button" id="startCook">ابدئي وضع الطبخ ↗</button><button id="detailTray">${bakingTray.includes(r.id)?'✓ أزيليها من الصينية':'+ أضيفيها للصينية'}</button><button class="bake-stamp-button" id="markBaked">✦ خبزتها!</button><button id="modalFavorite">${r.favorite?'♥ أزيلي من المفضلة':'♡ أضيفي للمفضلة'}</button></div><div class="rating-row"><span>تقييمك:</span><span class="stars">${[1,2,3,4,5].map(n=>`<button class="${n<=r.rating?'selected':''}" data-rate="${n}" aria-label="${n} نجوم">★</button>`).join('')}</span><span>اختاري عدد النجوم</span></div><div class="notes-box"><label for="recipeNote">ملاحظتي بعد التجربة</label><textarea id="recipeNote" rows="2" placeholder="مثلاً: أزيد القرفة المرة الجاية...">${escapeHtml(r.note||'')}</textarea></div>`;showModal(document.querySelector('#recipeModal'))}
function toggleFavorite(id){const r=recipes.find(x=>x.id===id);if(!r)return;r.favorite=!r.favorite;save();render();if(currentRecipe?.id===id)openRecipe(id);showToast(r.favorite?'انضافت لمفضّلتك ♡':'انشالت من المفضّلة')}
function closeAll(){document.querySelectorAll('.modal-backdrop').forEach(x=>hideModal(x))}
function startCook(){if(!currentRecipe)return;cookStep=0;document.querySelector('#recipeModal').classList.add('hidden');const el=document.createElement('div');el.className='cook-mode';el.id='cookMode';el.innerHTML=`<button class="cook-close" aria-label="إنهاء وضع الطبخ">×</button><div class="cook-inner"><span class="eyebrow">JURI COOKS · وضع الطبخ</span><div class="step-num"></div><div class="step-text"></div><div class="oven-timer"><span id="ovenTimerLabel">مؤقّت الفرن جاهز</span><button id="ovenTimerButton">شغّلي مؤقّت الفرن ⏱</button></div><div class="cook-controls"><button class="secondary" id="cookPrev">← الخطوة السابقة</button><button id="cookNext">الخطوة التالية →</button></div></div>`;document.body.append(el);document.body.style.overflow='hidden';el.querySelector('.cook-close').onclick=()=>{clearOvenTimer();el.remove();showModal(document.querySelector('#recipeModal'))};el.querySelector('#ovenTimerButton').onclick=toggleOvenTimer;el.querySelector('#cookPrev').onclick=()=>{if(cookStep>0){cookStep--;updateCook()}};el.querySelector('#cookNext').onclick=()=>{if(cookStep<currentRecipe.steps.length-1){cookStep++;updateCook()}else{clearOvenTimer();el.remove();document.body.style.overflow='';hideModal(document.querySelector('#recipeModal'));showToast('بالعافية يا جوري! ♡');celebrate()}};updateCook()}
function updateCook(){const el=document.querySelector('#cookMode');el.querySelector('.step-num').textContent=`STEP ${String(cookStep+1).padStart(2,'0')} / ${String(currentRecipe.steps.length).padStart(2,'0')}`;el.querySelector('.step-text').textContent=currentRecipe.steps[cookStep];el.querySelector('#cookPrev').disabled=cookStep===0;el.querySelector('#cookNext').textContent=cookStep===currentRecipe.steps.length-1?'خلصت، بالعافية ♡':'الخطوة التالية →'}
function addRecipe(e){e.preventDefault();const f=new FormData(e.currentTarget);const recipe={id:`custom-${Date.now()}`,title:f.get('title').trim(),category:f.get('category'),tags:[f.get('category')],time:Number(f.get('time'))||30,emoji:'🧁',art:'custom',description:f.get('description').trim()||'وصفة جديدة انضافت إلى دفتر جوري.',servings:'على مزاجك',ingredients:f.get('ingredients').split('\n').map(s=>s.trim()).filter(Boolean),steps:f.get('steps').split('\n').map(s=>s.trim()).filter(Boolean),favorite:false,rating:0,note:''};recipes.unshift(recipe);save();render();e.currentTarget.reset();hideModal(document.querySelector('#addModal'));showToast('انحفظت وصفتك في الدفتر ♡');openRecipe(recipe.id)}
document.querySelector('#filters').addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(!b)return;activeCategory=b.dataset.category;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));render()});document.querySelector('#searchInput').addEventListener('input',render);document.querySelector('.search-toggle').addEventListener('click',()=>{document.querySelector('#searchInput').focus();document.querySelector('#recipes').scrollIntoView({behavior:'smooth'})});document.querySelector('#recipeGrid').addEventListener('click',e=>{const fav=e.target.closest('[data-fav]');const open=e.target.closest('[data-open]');if(fav)toggleFavorite(fav.dataset.fav);if(open)openRecipe(open.dataset.open)});document.querySelector('#recipeDetail').addEventListener('click',e=>{const unit=e.target.closest('[data-unit]');if(unit){setMeasurementMode(unit.dataset.unit);return}const rate=e.target.closest('[data-rate]');if(rate&&currentRecipe){currentRecipe.rating=Number(rate.dataset.rate);save();openRecipe(currentRecipe.id)}if(e.target.id==='startCook')startCook();if(e.target.id==='modalFavorite'&&currentRecipe)toggleFavorite(currentRecipe.id)});document.querySelector('#recipeDetail').addEventListener('input',e=>{if(e.target.id==='recipeNote'&&currentRecipe){currentRecipe.note=e.target.value;save()}});document.querySelector('#openAdd').addEventListener('click',()=>showModal(document.querySelector('#addModal')));document.querySelector('#addRecipeForm').addEventListener('submit',addRecipe);document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>closeAll()));document.querySelectorAll('.modal-backdrop').forEach(b=>b.addEventListener('click',e=>{if(e.target===b)closeAll()}));document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeAll();const mode=document.querySelector('#cookMode');if(mode){mode.remove();document.body.style.overflow=''}}});document.querySelector('#randomRecipe').addEventListener('click',startPick);document.querySelector('#viewAll').addEventListener('click',()=>{activeCategory='الكل';document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.category==='الكل'));document.querySelector('#searchInput').value='';render();document.querySelector('#recipes').scrollIntoView({behavior:'smooth'})});
render();

// A gentle bakery entrance, warm floating embers, and scroll reveals.
(function startBakeryAtmosphere(){
  const entry=document.querySelector('#bakeryEntry');
  const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  if(entry&&!reducedMotion&&!sessionStorage.getItem('juri-bakery-entered')){
    document.body.classList.add('entering-bakery');
    window.setTimeout(()=>entry.classList.add('open'),360);
    window.setTimeout(()=>{entry.classList.add('done');document.body.classList.remove('entering-bakery');sessionStorage.setItem('juri-bakery-entered','1')},1580);
  }else if(entry)entry.classList.add('done');

  const embers=document.querySelector('#embers');
  if(embers&&!reducedMotion){for(let i=0;i<22;i++){const ember=document.createElement('i');ember.className='ember';ember.style.left=`${Math.random()*100}%`;ember.style.setProperty('--duration',`${9+Math.random()*12}s`);ember.style.setProperty('--delay',`${-Math.random()*18}s`);ember.style.setProperty('--drift',`${Math.round(Math.random()*100-50)}px`);embers.append(ember)}}

  const revealTargets=document.querySelectorAll('.welcome-strip,.recipe-section,.note-section,.footer');
  let revealObserver;
  if('IntersectionObserver'in window&&!reducedMotion){
    revealObserver=new IntersectionObserver(items=>items.forEach(item=>{if(item.isIntersecting){item.target.classList.add('revealed');revealObserver.unobserve(item.target)}}),{threshold:.12});
    revealTargets.forEach(el=>{el.classList.add('reveal-on-scroll');revealObserver.observe(el)});
    const observeCards=()=>document.querySelectorAll('.recipe-card:not(.reveal-on-scroll)').forEach((card,i)=>{card.classList.add('reveal-on-scroll');card.style.setProperty('--reveal-delay',`${Math.min(i,5)*90}ms`);revealObserver.observe(card)});
    observeCards();new MutationObserver(observeCards).observe(document.querySelector('#recipeGrid'),{childList:true});
  }else revealTargets.forEach(el=>el.classList.add('revealed'));

  const progress=document.querySelector('#scrollProgress');
  const updateProgress=()=>{const room=document.documentElement.scrollHeight-window.innerHeight;progress.style.transform=`scaleX(${room>0?window.scrollY/room:0})`};
  window.addEventListener('scroll',updateProgress,{passive:true});updateProgress();

  const scene=document.querySelector('.bakery-scene');
  if(scene&&!reducedMotion){scene.addEventListener('pointermove',e=>{const r=scene.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;scene.style.setProperty('--mx',`${x*-9}px`);scene.style.setProperty('--my',`${y*-7}px`)});scene.addEventListener('pointerleave',()=>{scene.style.setProperty('--mx','0px');scene.style.setProperty('--my','0px')})}
})();

// Personal baking tray, baker's stamps, oven countdown, and a rolling daily pick.
function loadTray(){try{return JSON.parse(localStorage.getItem(TRAY_STORE))||[]}catch{return []}}
function loadChecks(){try{return new Set(JSON.parse(localStorage.getItem(CHECK_STORE))||[])}catch{return new Set()}}
function saveTray(){localStorage.setItem(TRAY_STORE,JSON.stringify(bakingTray));localStorage.setItem(CHECK_STORE,JSON.stringify([...checkedItems]));updateCounts()}
function toggleTray(id){if(bakingTray.includes(id)){bakingTray=bakingTray.filter(x=>x!==id);for(const key of [...checkedItems])if(key.startsWith(`${id}:`))checkedItems.delete(key);showToast('انشالت من صينية التجهيز')}else{bakingTray.push(id);showToast('انضافت لصينيتك ✨')}saveTray();render();renderTray();if(currentRecipe?.id===id)openRecipe(id)}
function openTray(){renderTray();document.querySelector('#trayBackdrop').classList.remove('hidden');document.querySelector('#trayDrawer').classList.add('open');document.querySelector('#trayDrawer').setAttribute('aria-hidden','false');document.body.classList.add('tray-open')}
function closeTray(){document.querySelector('#trayBackdrop').classList.add('hidden');document.querySelector('#trayDrawer').classList.remove('open');document.querySelector('#trayDrawer').setAttribute('aria-hidden','true');document.body.classList.remove('tray-open')}
function renderTray(){const host=document.querySelector('#trayContent');const selected=recipes.filter(r=>bakingTray.includes(r.id));if(!selected.length){host.innerHTML='<div class="tray-empty"><span>🥐</span><b>صينيتك لسه فاضية</b><p>ضيفي وصفة من الواجهة، وأنا أرتّب لك المقادير هنا.</p><button class="tray-browse" id="browseRecipes">اختاري من الواجهة ↗</button></div>';return}const known=selected.find(r=>starterMeasures[r.id]);host.innerHTML=`<div class="tray-intro">${selected.length} ${selected.length===1?'وصفة جاهزة':'وصفات جاهزة'} لوقت الخَبز ♡${known?measurementControl(known):''}</div>${selected.map(r=>`<section class="tray-recipe"><div class="tray-recipe-head"><span>${escapeHtml(r.emoji||'🥐')}</span><div><b>${escapeHtml(r.title)}</b><small>${r.ingredients.length} مكوّن · ${r.time||30} دقيقة</small></div><button data-remove-tray="${escapeHtml(r.id)}" aria-label="إزالة ${escapeHtml(r.title)}">×</button></div><ul>${r.ingredients.map((ingredient,index)=>{const key=`${r.id}:${index}`;return `<li class="${checkedItems.has(key)?'checked':''}"><label><input type="checkbox" data-check="${escapeHtml(key)}" ${checkedItems.has(key)?'checked':''}><span>${escapeHtml(ingredientLabel(r,index))}</span></label></li>`}).join('')}</ul><button class="tray-open-recipe" data-open="${escapeHtml(r.id)}">افتحي الوصفة <span>←</span></button></section>`).join('')}<div class="tray-footer"><button id="copyTrayList">انسخي قائمة المقادير</button><button class="clear-tray" id="clearTray">افرغي الصينية</button></div>`}
function markBaked(id){const r=recipes.find(x=>x.id===id);if(!r)return;r.bakeCount=(r.bakeCount||0)+1;r.lastBakedAt=new Date().toISOString();save();render();openRecipe(id);celebrate();showToast('انختمت في سجل مخبوزاتك! ✦')}
function celebrate(){const layer=document.querySelector('#celebrationLayer');const colors=['#f2c66d','#e68d76','#91a07c','#fff0cb','#c9805f'];for(let i=0;i<42;i++){const piece=document.createElement('i');piece.className='confetti-piece';piece.textContent=i%5===0?'✦':'';piece.style.left=`${Math.random()*100}%`;piece.style.background=colors[i%colors.length];piece.style.setProperty('--fall-delay',`${Math.random()*.35}s`);piece.style.setProperty('--fall-time',`${1.2+Math.random()*.9}s`);piece.style.setProperty('--spin',`${Math.round(Math.random()*900-450)}deg`);piece.style.setProperty('--confetti-drift',`${Math.round(Math.random()*180-90)}px`);layer.append(piece);setTimeout(()=>piece.remove(),2600)}}
function playBell(){try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;const ctx=new Audio();[880,1175].forEach((hz,i)=>{const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='sine';osc.frequency.value=hz;gain.gain.setValueAtTime(.0001,ctx.currentTime+i*.14);gain.gain.exponentialRampToValueAtTime(.08,ctx.currentTime+i*.14+.025);gain.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+i*.14+.55);osc.connect(gain);gain.connect(ctx.destination);osc.start(ctx.currentTime+i*.14);osc.stop(ctx.currentTime+i*.14+.58)});setTimeout(()=>ctx.close(),1100)}catch{}}
function formatTime(seconds){return `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`}
function toggleOvenTimer(){const label=document.querySelector('#ovenTimerLabel'),button=document.querySelector('#ovenTimerButton');if(ovenTimerHandle){clearInterval(ovenTimerHandle);ovenTimerHandle=null;button.textContent='استأنفي المؤقّت';label.textContent=`متوقف عند ${formatTime(ovenSeconds)}`;return}if(!ovenSeconds){const minutes=currentRecipe?.id==='cinnamon-rolls'?20:currentRecipe?.id==='quick-sandwich-bread'?3:Math.min(Number(currentRecipe?.time)||15,60);ovenSeconds=minutes*60}button.textContent='إيقاف مؤقّت الفرن';label.textContent=`باقي ${formatTime(ovenSeconds)}`;ovenTimerHandle=setInterval(()=>{ovenSeconds--;label.textContent=`باقي ${formatTime(ovenSeconds)}`;if(ovenSeconds<=0){clearOvenTimer();label.textContent='خلص الوقت! طلّعيها من الفرن ♡';button.textContent='ابدئي مؤقّتًا جديدًا';playBell();celebrate();showToast('تينغ! مؤقّت الفرن خلص 🔔')}},1000)}
function clearOvenTimer(){if(ovenTimerHandle)clearInterval(ovenTimerHandle);ovenTimerHandle=null;ovenSeconds=0}
function startPick(){if(!recipes.length)return;const overlay=document.querySelector('#pickOverlay'),spinner=document.querySelector('#pickSpinner'),title=document.querySelector('#pickTitle'),open=document.querySelector('#pickOpen');overlay.classList.remove('hidden');overlay.classList.remove('picked');open.classList.add('hidden');title.textContent='من أي رف نبدأ؟';let tick=0;const chosen=recipes[Math.floor(Math.random()*recipes.length)];clearInterval(pickInterval);pickInterval=setInterval(()=>{const item=recipes[tick++%recipes.length];spinner.textContent=item.emoji||'🥐';title.textContent=item.title;spinner.classList.toggle('spin-flip')},95);setTimeout(()=>{clearInterval(pickInterval);pickInterval=null;spinner.textContent=chosen.emoji||'🥐';title.textContent=chosen.title;open.dataset.open=chosen.id;open.classList.remove('hidden');overlay.classList.add('picked')},1450)}

document.querySelector('#recipeGrid').addEventListener('click',e=>{const button=e.target.closest('[data-tray]');if(button){e.preventDefault();toggleTray(button.dataset.tray)}});
document.querySelector('#recipeDetail').addEventListener('click',e=>{if(e.target.id==='detailTray'&&currentRecipe)toggleTray(currentRecipe.id);if(e.target.id==='markBaked'&&currentRecipe)markBaked(currentRecipe.id)});
document.querySelector('#openTray').addEventListener('click',openTray);document.querySelector('#closeTray').addEventListener('click',closeTray);document.querySelector('#trayBackdrop').addEventListener('click',closeTray);
document.querySelector('#trayDrawer').addEventListener('click',e=>{const unit=e.target.closest('[data-unit]');if(unit){setMeasurementMode(unit.dataset.unit);return}const remove=e.target.closest('[data-remove-tray]');if(remove){toggleTray(remove.dataset.removeTray);return}if(e.target.id==='browseRecipes'){closeTray();document.querySelector('#recipes').scrollIntoView({behavior:'smooth'});return}if(e.target.id==='clearTray'){bakingTray=[];checkedItems.clear();saveTray();render();renderTray();showToast('صينيتك صارت جاهزة لوصفات جديدة');return}if(e.target.id==='copyTrayList'){const lines=recipes.filter(r=>bakingTray.includes(r.id)).flatMap(r=>[r.title,...r.ingredients.map((x,i)=>`☐ ${ingredientLabel(r,i)}`),'']);if(navigator.clipboard?.writeText)navigator.clipboard.writeText(lines.join('\n')).then(()=>showToast('قائمة مقاديرك جاهزة للنسخ ♡')).catch(()=>showToast('ما قدرنا ننسخ القائمة على هذا الجهاز'));else showToast('النسخ غير متاح في هذا المتصفح');return}const open=e.target.closest('[data-open]');if(open){closeTray();openRecipe(open.dataset.open)}});
document.querySelector('#trayDrawer').addEventListener('change',e=>{const checkbox=e.target.closest('[data-check]');if(!checkbox)return;if(checkbox.checked)checkedItems.add(checkbox.dataset.check);else checkedItems.delete(checkbox.dataset.check);saveTray();checkbox.closest('li').classList.toggle('checked',checkbox.checked)});
document.querySelector('#mobileDailyPick').addEventListener('click',startPick);document.querySelector('#mobileTray').addEventListener('click',openTray);
document.querySelector('#pickOpen').addEventListener('click',e=>{const id=e.currentTarget.dataset.open;document.querySelector('#pickOverlay').classList.add('hidden');openRecipe(id)});document.querySelector('#closePick').addEventListener('click',()=>document.querySelector('#pickOverlay').classList.add('hidden'));document.querySelector('#pickOverlay').addEventListener('click',e=>{if(e.target.id==='pickOverlay')e.currentTarget.classList.add('hidden')});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeTray();document.querySelector('#pickOverlay').classList.add('hidden');if(document.querySelector('#cookMode'))clearOvenTimer()}});
updateCounts();
